FROM golang:1.13-alpine

RUN set -ex \
  && echo "==> Changine Repositories..." \
  && sed -i -e"s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/" /etc/apk/repositories \
  && apk add --no-cache --virtual .build-deps tzdata \
  && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone \
  && apk del .build-deps
